# Parmesh Mohan Walunj
# 1002149428
indexMapping = {
    "properties":{
        "Poster_Link":{
            "type":"text"
        },
        "Series_Title":{
            "type":"text"
        },
        "Released_Year":{
            "type":"long"
        },
        "Certificate":{
            "type":"text"
        },
        "Runtime":{
            "type":"text"
        },
        "Genre":{
            "type":"text",
        },
        "IMDB_Rating":{
            "type":"long"
        },
        "Overview":{
            "type":"text"
        },
        "Meta_score":{
            "type":"long"
        },
        "Director":{
            "type":"text"
        },
        "Star1":{
            "type":"text"
        },
        "Star2":{
            "type":"text"
        },
        "Star3":{
            "type":"text"
        },
        "Star4":{
            "type":"text"
        },
        "No_of_Votes":{
            "type":"long"
        },
        "Gross":{
            "type":"long"
        },
        "Cleaned_Text":{
            "type":"text"
        }, 
        "vectoredDetails":{
            "type":"dense_vector",
            "dims":768,
            "index": True,
            "similarity":"l2_norm"
        }, 
    }
}